# Amazon Review 2023
Amazon Reviews dataset is large-scale dataset collected in 2023 by McAuley Lab, and it includes rich features such as:
- User Reviews (ratings, text, helpfulness votes, etc.);
- Item Metadata (descriptions, price, raw image, etc.);
- Links (user-item / bought together graphs).

Related Information
- HP: https://amazon-reviews-2023.github.io/
- paper: [Bridging Language and Items for Retrieval and Recommendation](https://arxiv.org/abs/2403.03952)

In [1]:
from ml_sandbox_libs.data.amazon_reviews_dataset import fetch_dataset, fetch_metadata

In [2]:
dataset_dict = fetch_dataset(category="Video_Games", dataset_type="0core_last_out_w_his")
df = dataset_dict["train"].to_polars()
df.head()

2025-04-11 21:00:21.409 | INFO     | ml_sandbox_libs.data.amazon_reviews_dataset:fetch_dataset:38 - Fetching Amazon Reviews 2023 dataset

shape: (5, 5)
┌──────────────────────────────┬─────────────┬────────┬───────────────┬───────────────────────┐
│ user_id                      ┆ parent_asin ┆ rating ┆ timestamp     ┆ history               │
│ ---                          ┆ ---         ┆ ---    ┆ ---           ┆ ---                   │
│ str                          ┆ str         ┆ str    ┆ str           ┆ str                   │
╞══════════════════════════════╪═════════════╪════════╪═══════════════╪═══════════════════════╡
│ AG6BAEKWLCWH2TW3KKLVK773YF6A ┆ B0B36HX334  ┆ 1.0    ┆ 1523313903402 ┆                       │
│ AG6BAEKWLCWH2TW3KKLVK773YF6A ┆ B001AW156U  ┆ 4.0    ┆ 1523314072900 ┆ B0B36HX334            │
│ AEVPPTMG43C6GWSR7I2UGRQN7WFQ ┆ B08R5B7YS4  ┆ 1.0    ┆ 1611459666223 ┆                       │
│ AEVPPTMG43C6GWSR7I2UGRQN7WFQ ┆ B0863MT183  ┆ 4.0    ┆ 1613701986538 ┆ B08R5B7YS4            │
│ AEVPPTMG43C6GWSR7I2UGRQN7WFQ ┆ B08P8P7686  ┆ 5.0    ┆ 1613702112995 ┆ B08R5B7YS4 B0863MT183 │
└──────────────────────────────┴─────────────┴────────┴───────────────┴───────────────────────┘

In [3]:
print("Dataset Size")
print(
    f"train: {len(dataset_dict["train"])}, valid: {len(dataset_dict["valid"])}, test: {len(dataset_dict["test"])}"
)

Dataset Size
train: 1045048, valid: 743796, test: 2766656

The dataset schema is as follows: https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023#for-user-reviews

| Field            | Type     | Explanation                                                                                                                                                                               |
|------------------|----------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| user_id          | str      | ID of the reviewer                                                                                                                                                                       |
| parent_asin      | str      | Parent ID of the product. Note: Products with different colors, styles, sizes usually belong to the same parent ID. The “asin” in previous Amazon datasets is actually parent ID. **Please use parent ID to find product meta.** |
| rating           | float    | Rating of the product (from 1.0 to 5.0).                                                                                                                                                   |
| timestamp        | int      | Time of the review (unix time)                                                                                                                                                           |
| history | str     | parent_asin list which was bought by user before. The separator is ' '                                                                                                                                                               |

In [4]:
metadata_dataset = fetch_metadata(category="Video_Games")
metadata_df = metadata_dataset.to_polars().select(["parent_asin", "title", "categories"])
metadata_df.head(5)

2025-04-11 21:00:25.605 | INFO     | ml_sandbox_libs.data.amazon_reviews_dataset:fetch_metadata:58 - Fetching Amazon Reviews 2023 metadata

shape: (5, 3)
┌─────────────┬─────────────────────────────────┬─────────────────────────────────┐
│ parent_asin ┆ title                           ┆ categories                      │
│ ---         ┆ ---                             ┆ ---                             │
│ str         ┆ str                             ┆ list[str]                       │
╞═════════════╪═════════════════════════════════╪═════════════════════════════════╡
│ B000FH0MHO  ┆ Dash 8-300 Professional Add-On  ┆ ["Video Games", "PC", "Games"]  │
│ B00069EVOG  ┆ Phantasmagoria: A Puzzle of Fl… ┆ ["Video Games", "PC", "Games"]  │
│ B00Z9TLVK0  ┆ NBA 2K17 - Early Tip Off Editi… ┆ ["Video Games", "PlayStation 4… │
│ B07SZJZV88  ┆ Nintendo Selects: The Legend o… ┆ ["Video Games", "Legacy System… │
│ B002WH4ZJG  ┆ Thrustmaster Elite Fitness Pac… ┆ ["Video Games", "Legacy System… │
└─────────────┴─────────────────────────────────┴─────────────────────────────────┘

In [5]:
print(f"Parent Asin Size: {len(metadata_df)}")

Parent Asin Size: 137269

The metadata schema is as follows: https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023#for-item-metadata

| Field           | Type   | Explanation                                                                                                                                                             |
|-----------------|--------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| parent_asin     | str    | Parent ID of the product.                                                                                                                                                |
| title           | str    | Name of the product.                                                                                                                                                     |
| categories      | list   | Hierarchical categories of the product.                                                                                                                                  |