# Amazon Review 2023
Amazon Reviews dataset is large-scale dataset collected in 2023 by McAuley Lab, and it includes rich features such as:
- User Reviews (ratings, text, helpfulness votes, etc.);
- Item Metadata (descriptions, price, raw image, etc.);
- Links (user-item / bought together graphs).

Related Information
- HP: https://amazon-reviews-2023.github.io/
- paper: [Bridging Language and Items for Retrieval and Recommendation](https://arxiv.org/abs/2403.03952)

In [1]:
import pathlib

from ml_sandbox_libs.data.amazon_reviews_dataset import (
    AmazonReviewsSeqRecDataModule,
    fetch_dataset,
    fetch_metadata,
    bipartite_graph_preprocess_dataset,
)

In [2]:
dataset_dict = fetch_dataset(category="Video_Games", dataset_type="0core_timestamp_w_his")
df = dataset_dict["train"].to_polars()
df.head()

2025-06-08 17:34:21.916 | INFO     | ml_sandbox_libs.data.amazon_reviews_dataset:fetch_dataset:39 - Fetching Amazon Reviews 2023 dataset

shape: (5, 5)
┌──────────────────────────────┬─────────────┬────────┬───────────────┬────────────┐
│ user_id                      ┆ parent_asin ┆ rating ┆ timestamp     ┆ history    │
│ ---                          ┆ ---         ┆ ---    ┆ ---           ┆ ---        │
│ str                          ┆ str         ┆ str    ┆ str           ┆ str        │
╞══════════════════════════════╪═════════════╪════════╪═══════════════╪════════════╡
│ AGCI7FAH4GL5FI65HYLKWTMFZ2CQ ┆ B07SRWRH5D  ┆ 5.0    ┆ 1587051114941 ┆            │
│ AGCI7FAH4GL5FI65HYLKWTMFZ2CQ ┆ B07DK1H3H5  ┆ 4.0    ┆ 1608186804795 ┆ B07SRWRH5D │
│ AGXVBIUFLFGMVLATYXHJYL4A5Q7Q ┆ B07MFMFW34  ┆ 5.0    ┆ 1490877431000 ┆            │
│ AFTC6ZR5IKNRDG5JCPVNVMU3XV2Q ┆ B00HUWA45W  ┆ 5.0    ┆ 1427591932000 ┆            │
│ AFTC6ZR5IKNRDG5JCPVNVMU3XV2Q ┆ B0BCHWZX95  ┆ 5.0    ┆ 1577637634017 ┆ B00HUWA45W │
└──────────────────────────────┴─────────────┴────────┴───────────────┴────────────┘

In [3]:
print("Dataset Size")
print(
    f"train: {len(dataset_dict['train'])}, valid: {len(dataset_dict['valid'])}, test: {len(dataset_dict['test'])}"
)

Dataset Size
train: 3847041, valid: 344592, test: 363867

The dataset schema is as follows: https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023#for-user-reviews

| Field            | Type     | Explanation                                                                                                                                                                               |
|------------------|----------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| user_id          | str      | ID of the reviewer                                                                                                                                                                       |
| parent_asin      | str      | Parent ID of the product. Note: Products with different colors, styles, sizes usually belong to the same parent ID. The “asin” in previous Amazon datasets is actually parent ID. **Please use parent ID to find product meta.** |
| rating           | float    | Rating of the product (from 1.0 to 5.0).                                                                                                                                                   |
| timestamp        | int      | Time of the review (unix time)                                                                                                                                                           |
| history | str     | parent_asin list which was bought by user before. The separator is ' '                                                                                                                                                               |

In [4]:
metadata_dataset = fetch_metadata(category="Video_Games")
metadata_df = metadata_dataset.to_polars().select(["parent_asin", "title", "categories"])
metadata_df.head(5)

2025-06-08 17:34:24.881 | INFO     | ml_sandbox_libs.data.amazon_reviews_dataset:fetch_metadata:59 - Fetching Amazon Reviews 2023 metadata

shape: (5, 3)
┌─────────────┬─────────────────────────────────┬─────────────────────────────────┐
│ parent_asin ┆ title                           ┆ categories                      │
│ ---         ┆ ---                             ┆ ---                             │
│ str         ┆ str                             ┆ list[str]                       │
╞═════════════╪═════════════════════════════════╪═════════════════════════════════╡
│ B000FH0MHO  ┆ Dash 8-300 Professional Add-On  ┆ ["Video Games", "PC", "Games"]  │
│ B00069EVOG  ┆ Phantasmagoria: A Puzzle of Fl… ┆ ["Video Games", "PC", "Games"]  │
│ B00Z9TLVK0  ┆ NBA 2K17 - Early Tip Off Editi… ┆ ["Video Games", "PlayStation 4… │
│ B07SZJZV88  ┆ Nintendo Selects: The Legend o… ┆ ["Video Games", "Legacy System… │
│ B002WH4ZJG  ┆ Thrustmaster Elite Fitness Pac… ┆ ["Video Games", "Legacy System… │
└─────────────┴─────────────────────────────────┴─────────────────────────────────┘

In [5]:
print(f"Parent Asin Size: {len(metadata_df)}")

Parent Asin Size: 137269

The metadata schema is as follows: https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023#for-item-metadata

| Field           | Type   | Explanation                                                                                                                                                             |
|-----------------|--------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| parent_asin     | str    | Parent ID of the product.                                                                                                                                                |
| title           | str    | Name of the product.                                                                                                                                                     |
| categories      | list   | Hierarchical categories of the product.                                                                                                                                  |

In [6]:
datamodule = AmazonReviewsSeqRecDataModule(
    save_dir=pathlib.Path("../data"),
    batch_size=2,
    num_workers=4,
    max_seq_len=5,
    neg_sample_size=2,
    sampling_val_test=True,
    eval_negative_sample_size=10,
    filter_no_history=False,
)

datamodule.prepare_data()
datamodule.setup(stage="fit")
train_dataloader = datamodule.train_dataloader()
batch = next(iter(train_dataloader))

2025-06-08 17:34:26.348 | INFO     | ml_sandbox_libs.data.amazon_reviews_dataset:prepare_data:682 - Loading preprocessed dataset

In [7]:
datamodule.train_df.head(5)

shape: (5, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ user_id   ┆ user_inde ┆ parent_as ┆ item_inde ┆ … ┆ history   ┆ history_i ┆ history_c ┆ history_ │
│ ---       ┆ x         ┆ in        ┆ x         ┆   ┆ ---       ┆ ndex      ┆ ategory   ┆ category │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ list[str] ┆ ---       ┆ ---       ┆ _index   │
│           ┆ i64       ┆ str       ┆ i64       ┆   ┆           ┆ list[i64] ┆ list[str] ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ list[i64 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ]        │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ AGCI7FAH4 ┆ 1216183   ┆ B07SRWRH5 ┆ 30008     ┆ … ┆ []        ┆ []        ┆ []        ┆ []       │
│ GL5FI65HY ┆           ┆ D         ┆           ┆   ┆           ┆           ┆           ┆          │
│ LKWTMFZ2C ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Q         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ AGCI7FAH4 ┆ 1216183   ┆ B07DK1H3H ┆ 27742     ┆ … ┆ ["B07SRWR ┆ [30008]   ┆ ["Video   ┆ [164]    │
│ GL5FI65HY ┆           ┆ 5         ┆           ┆   ┆ H5D"]     ┆           ┆ Games/Pla ┆          │
│ LKWTMFZ2C ┆           ┆           ┆           ┆   ┆           ┆           ┆ yStation  ┆          │
│ Q         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4/Ga…     ┆          │
│ AGXVBIUFL ┆ 1576453   ┆ B07MFMFW3 ┆ 29081     ┆ … ┆ []        ┆ []        ┆ []        ┆ []       │
│ FGMVLATYX ┆           ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ HJYL4A5Q7 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Q         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ AFTC6ZR5I ┆ 961308    ┆ B00HUWA45 ┆ 19292     ┆ … ┆ []        ┆ []        ┆ []        ┆ []       │
│ KNRDG5JCP ┆           ┆ W         ┆           ┆   ┆           ┆           ┆           ┆          │
│ VNVMU3XV2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Q         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ AFTC6ZR5I ┆ 961308    ┆ B0BCHWZX9 ┆ 33732     ┆ … ┆ ["B00HUWA ┆ [19292]   ┆ ["Video   ┆ [177]    │
│ KNRDG5JCP ┆           ┆ 5         ┆           ┆   ┆ 45W"]     ┆           ┆ Games/Xbo ┆          │
│ VNVMU3XV2 ┆           ┆           ┆           ┆   ┆           ┆           ┆ x One/Acc ┆          │
│ Q         ┆           ┆           ┆           ┆   ┆           ┆           ┆ esso…     ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
batch.user_index, batch.pos_item_index, batch.neg_item_indexes, batch.item_history

(tensor([2017790, 1921071]),
 tensor([24566, 31019]),
 tensor([[21179,  5833],
         [17200, 20326]]),
 tensor([[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]))

## Bipartite Graph

In [9]:
(
    train_df,
    val_df,
    test_df,
    user2index,
    item2index,
    category2index,
    item_index_2_category_index,
) = bipartite_graph_preprocess_dataset(dataset_dict=dataset_dict, metadata=metadata_dataset)

2025-06-08 17:35:27.278 | INFO     | ml_sandbox_libs.data.amazon_reviews_dataset:bipartite_graph_preprocess_dataset:872 - Preprocessing the dataset for bipartite graph

In [10]:
train_df.head(5)

shape: (5, 9)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬────────┬───────────┬───────────┐
│ user_id    ┆ user_index ┆ parent_as ┆ item_inde ┆ … ┆ category_ ┆ rating ┆ timestamp ┆ num_ratin │
│ ---        ┆ ---        ┆ in        ┆ x         ┆   ┆ index     ┆ ---    ┆ ---       ┆ gs        │
│ str        ┆ i64        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64    ┆ i64       ┆ ---       │
│            ┆            ┆ str       ┆ i64       ┆   ┆ i64       ┆        ┆           ┆ u32       │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪════════╪═══════════╪═══════════╡
│ AELHFSFNZG ┆ 291949     ┆ B003NSLGW ┆ 13036     ┆ … ┆ 82        ┆ 5.0    ┆ 146348798 ┆ 1         │
│ MUKRQ6Q2MY ┆            ┆ 2         ┆           ┆   ┆           ┆        ┆ 1000      ┆           │
│ N367HZUA   ┆            ┆           ┆           ┆   ┆           ┆        ┆           ┆           │
│ AFQTTZF33C ┆ 920300     ┆ B016XBGWA ┆ 22448     ┆ … ┆ 136       ┆ 5.0    ┆ 148250573 ┆ 1         │
│ BXX25UDHM4 ┆            ┆ Q         ┆           ┆   ┆           ┆        ┆ 0000      ┆           │
│ IS7ISSTA   ┆            ┆           ┆           ┆   ┆           ┆        ┆           ┆           │
│ AE2PPMOOEK ┆ 11416      ┆ B001VLFCV ┆ 11126     ┆ … ┆ 65        ┆ 4.0    ┆ 129296232 ┆ 1         │
│ DVEYFWW4EH ┆            ┆ E         ┆           ┆   ┆           ┆        ┆ 4000      ┆           │
│ VXMPKQMA   ┆            ┆           ┆           ┆   ┆           ┆        ┆           ┆           │
│ AEPDDADHBG ┆ 356792     ┆ B001C6GVI ┆ 9129      ┆ … ┆ 65        ┆ 4.0    ┆ 153396822 ┆ 1         │
│ VCZI7EGM7Q ┆            ┆ 6         ┆           ┆   ┆           ┆        ┆ 7912      ┆           │
│ 66BXMQ2Q   ┆            ┆           ┆           ┆   ┆           ┆        ┆           ┆           │
│ AGPWP7OQVN ┆ 1442193    ┆ B0000A2MA ┆ null      ┆ … ┆ 136       ┆ 4.0    ┆ 143128627 ┆ 1         │
│ UCDJDCKSG6 ┆            ┆ Q         ┆           ┆   ┆           ┆        ┆ 2000      ┆           │
│ KGGZ3L4A   ┆            ┆           ┆           ┆   ┆           ┆        ┆           ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴────────┴───────────┴───────────┘